import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { FaArrowLeft, FaInfoCircle } from 'react-icons/fa';

const TermsAndConditions = () => {
    const navigate = useNavigate();
    const [language, setLanguage] = useState('en');

    const termsData = {
        en: {
            title: 'Terms of Use',
            lastUpdated: 'Last Updated: December 2024',
            disclaimer: 'Disclaimer: In case of any inconsistency, the English version shall prevail.',
            intro: [
                'This document is an electronic record under the Information Technology Act, 2000 and applicable rules. This electronic record is generated by a computer system and does not require physical or digital signatures.',
                'APK Crackers Private Limited operates a digital platform that only facilitates enquiries between customers and licensed firecracker sellers. The Platform does not sell, book, store, transport, ship, or deliver firecrackers.',
                'By accessing or using this Platform, you agree to be bound by these Terms of Use.'
            ],
            agreementText: 'PLEASE READ THESE TERMS CAREFULLY BEFORE USING THE PLATFORM.',
            sections: [
                {
                    heading: '1. Platform Nature',
                    content: 'The Platform acts solely as a technology intermediary to enable communication and enquiry exchange between customers and licensed sellers. APK Crackers does not act as a seller, distributor, agent, or logistics provider.'
                },
                {
                    heading: '2. Eligibility',
                    content: 'The Platform is intended only for users who are 18 years of age or above and capable of entering legally binding contracts under Indian law.'
                },
                {
                    heading: '3. Enquiry & Quotation Process',
                    content: 'Customers may browse products and submit enquiries. Any prices shown are indicative only. Final pricing, availability, billing, and terms are decided offline directly between the customer and the seller.'
                },
                {
                    heading: '4. No Orders, Payments, or Delivery',
                    content: 'The Platform does not support online orders, shopping carts, payments, refunds, returns, shipping, or delivery. All transactions and fulfillment are handled offline between customers and licensed sellers.'
                },
                {
                    heading: '5. Seller Responsibility',
                    content: 'Sellers listed on the Platform are solely responsible for holding valid licenses, complying with the Explosives Act, Explosives Rules, transport laws, local authority permissions, and all applicable regulations.'
                },
                {
                    heading: '6. User Responsibilities',
                    content: 'Users agree not to misuse the Platform, submit false enquiries, or engage in unlawful activities. APK Crackers reserves the right to restrict access for violations.'
                },
                {
                    heading: '7. Limitation of Liability',
                    content: 'APK Crackers shall not be liable for any disputes, damages, losses, injuries, legal violations, or claims arising between customers and sellers. The Platform provides no guarantees regarding product quality, safety, legality, or delivery.'
                },
                {
                    heading: '8. Intellectual Property',
                    content: 'All Platform content, branding, and design are the intellectual property of APK Crackers Private Limited and may not be used without permission.'
                },
                {
                    heading: '9. Governing Law & Jurisdiction',
                    content: 'These Terms shall be governed by the laws of India. Courts at Sivakasi, Tamil Nadu shall have exclusive jurisdiction.'
                }
            ],
            grievance: {
                title: 'Grievance Officer',
                text: 'In accordance with the Information Technology Act, 2000 and applicable rules, grievance details are provided below:',
                details: {
                    name: 'Mr. Selvadhanush S',
                    role: 'Designation: Grievance Officer',
                    company: 'APK Crackers Private Limited',
                    address: 'Sivakasi, Tamil Nadu, India – 626123',
                    email: 'grievance.officer@apkcrackers.com',
                    phone: '+91 98765 43210',
                    time: 'Mon – Sat (9:00 AM – 6:00 PM)'
                }
            }
        }
    };

    const currentData = termsData[language];

    useEffect(() => {
        window.scrollTo(0, 0);
        document.title = `${currentData.title} - APK Crackers`;
    }, [language, currentData.title]);

    return (
        <div className="min-h-screen bg-gray-50">
            {/* Header */}
            <header className="bg-white border-b border-gray-200 sticky top-0 z-50 shadow-sm">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <button
                            onClick={() => navigate(-1)}
                            className="p-2 hover:bg-orange-50 rounded-full transition-colors text-orange-600"
                            aria-label="Go back"
                        >
                            <FaArrowLeft className="w-5 h-5" />
                        </button>
                        <h1 className="text-lg md:text-xl font-bold text-gray-900">
                            {currentData.title}
                        </h1>
                    </div>
                    <p className="text-xs md:text-sm text-gray-500 hidden sm:block">{currentData.lastUpdated}</p>
                </div>
            </header>

            {/* Main Content */}
            <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
                {/* Content Card */}
                <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 md:p-10">
                    {/* Disclaimer Alert */}
                    <div className="flex items-start gap-3 p-4 mb-8 bg-orange-50 border border-orange-200 rounded-lg">
                        <FaInfoCircle className="w-5 h-5 text-orange-600 flex-shrink-0 mt-0.5" />
                        <p className="text-sm text-gray-700 font-medium">
                            {currentData.disclaimer}
                        </p>
                    </div>

                    {/* Introduction */}
                    <div className="text-sm text-gray-600 mb-8 space-y-4 leading-relaxed">
                        {currentData.intro.map((paragraph, idx) => (
                            <p key={idx} className="text-justify">{paragraph}</p>
                        ))}
                        <p className="font-bold text-gray-800 mt-6 uppercase text-xs tracking-wide bg-gray-50 p-4 rounded-lg border-l-4 border-orange-500">
                            {currentData.agreementText}
                        </p>
                    </div>

                    <hr className="border-gray-200 my-8" />

                    {/* Dynamic Sections */}
                    <div className="space-y-8">
                        {currentData.sections.map((section, index) => (
                            <div key={index} className="pb-6 border-b border-gray-100 last:border-0">
                                <h2 className="text-base md:text-lg font-bold text-gray-900 mb-3 flex items-center gap-2">
                                    <span className="w-1 h-6 bg-orange-500 rounded"></span>
                                    {section.heading}
                                </h2>
                                <p className="text-sm text-gray-600 leading-7 text-justify pl-3">
                                    {section.content}
                                </p>
                            </div>
                        ))}
                    </div>

                    <hr className="border-gray-200 my-8" />

                    {/* Grievance Officer Section */}
                    <div className="mb-8">
                        <h2 className="text-base md:text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                            <span className="w-1 h-6 bg-orange-500 rounded"></span>
                            {currentData.grievance.title}
                        </h2>
                        <p className="text-sm text-gray-600 mb-6 pl-3">
                            {currentData.grievance.text}
                        </p>

                        <div className="bg-gradient-to-br from-orange-50 to-yellow-50 border border-orange-200 p-6 md:p-8 rounded-xl">
                            <p className="font-bold text-gray-900 text-lg md:text-xl mb-1">
                                {currentData.grievance.details.name}
                            </p>
                            <p className="mb-4 text-orange-600 font-semibold text-sm">
                                {currentData.grievance.details.role}
                            </p>

                            <div className="space-y-2 text-sm text-gray-700">
                                <p className="font-medium">{currentData.grievance.details.company}</p>
                                <p>{currentData.grievance.details.address}</p>

                                <div className="mt-4 pt-4 border-t border-orange-200 space-y-2.5">
                                    <p className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-2">
                                        <span className="font-semibold text-gray-900 min-w-[70px]">Email:</span>
                                        <a
                                            href={`mailto:${currentData.grievance.details.email} `}
                                            className="text-orange-600 hover:text-orange-700 hover:underline break-all"
                                        >
                                            {currentData.grievance.details.email}
                                        </a>
                                    </p>
                                    <p className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-2">
                                        <span className="font-semibold text-gray-900 min-w-[70px]">Phone:</span>
                                        <span>{currentData.grievance.details.phone}</span>
                                    </p>
                                    <p className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-2">
                                        <span className="font-semibold text-gray-900 min-w-[70px]">Hours:</span>
                                        <span>{currentData.grievance.details.time}</span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Footer */}
                    <div className="border-t border-gray-200 pt-6 mt-8 text-center">
                        <p className="text-xs text-gray-500">
                            © 2024 APK Crackers Private Limited. All Rights Reserved.
                        </p>
                    </div>
                </div>
            </main>
        </div>
    );
};

export default TermsAndConditions;
